services:
  sgivu-postgres:
    container_name: sgivu-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    env_file: .env.dev
    networks:
      - sgivu-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  sgivu-redis:
    container_name: sgivu-redis
    image: redis:7
    command: >
      sh -c "redis-server --requirepass \"${DEV_REDIS_PASSWORD}\""
    env_file: .env.dev
    ports:
      - "6379:6379"
    restart: always
    networks:
      - sgivu-network
    volumes:
      - redis-data:/data

  sgivu-config:
    container_name: sgivu-config
    image: stevenrq/sgivu-config:${TAG:-latest}
    ports:
      - "8888:8888"
    restart: always
    networks:
      - sgivu-network
    volumes:
      - ../../../../sgivu-config-repo:/config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/config-repo

  sgivu-discovery:
    container_name: sgivu-discovery
    image: stevenrq/sgivu-discovery:${TAG:-latest}
    ports:
      - "8761:8761"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev

networks:
  sgivu-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
